version: '3.8'

services:
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - 127.0.0.1:5001:5001 #5000 is used on macOS
    restart: unless-stopped
    
  backend:
    image: backend
    container_name: backend
    ports:
      - 127.0.0.1:8080:8080
    environment:
      REDIS_HOST: redis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: db
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    container_name: postgres
    ports:
      - 127.0.0.1:5432:5432