version: '3.8'

services:
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - 127.0.0.1:5001:5001 #5000 is used on macOS

  backend:
    image: backend
    container_name: backend
    ports:
      - 127.0.0.1:8080:8080

  redis:
    image: redis:alpine
    container_name: redis
    ports:
    - 127.0.0.1:6379:6379