services:
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - 127.0.0.1:5001:5000 #5000 is used on macOS
    restart: unless-stopped
    
  backend:
    image: backend
    container_name: backend
    ports:
      - 127.0.0.1:8081:8080
    environment:
      REDIS_HOST: redis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: db
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    container_name: postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "127.0.0.1:80:80"
    environment:
      - NGINX_PORT=80