version: '3.8'

services:

  simple-web-service:
    image: devopsdockeruh/simple-web-service

    volumes:
      - ./text.log:/usr/src/app/text.log # Mounting a local folder to the container logs folder
    container_name: simple-web-service

